auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create_auction, name="create"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("auction/<int:auction_id>", views.auctions, name="auction"),
    path("categories.html", views.categories, name="categories" )
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

CATEGORY = (
    ('1', 'Electronique'),
    ('2', 'Vetement'),
    ('3', 'Meubles'),
    ('4', 'Salle de bain'),
    ('5', 'Cuisine'),
    ('6', 'Toy'),
    ('7', 'Autre')
)

DURATIONS = (
    ('1', 'One day'),
    ('3', 'Three days'),
    ('7', 'One week'),
    ('14', 'Two weeks'),
    ('28', 'Four weeks')
)


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"

class Category(models.Model):
    category = models.CharField(max_length=1, choices=CATEGORY)

    def __str__(self):
        return f"{self.category}"

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bid")
    time = models.DateTimeField(auto_now_add=True)
    bid = models.DecimalField(max_digits=8, decimal_places=2)
    
    def __str__(self):
        return f"Last bid : {self.bid}$ - By : {self.user}"

class Commit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commit_user")
    comment = models.CharField(max_length=512)
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}: {self.comment}"

class Auction(models.Model):
    category = models.CharField(max_length=1, choices=CATEGORY)
    title_item = models.CharField(max_length=64)
    description_item = models.CharField(max_length=512)
    image_URL = models.URLField(blank=True)
    durations = models.CharField(max_length=2, choices=DURATIONS)
    closed = models.BooleanField(default=False)
    start_price = models.DecimalField(max_digits=8, decimal_places=2)
    time  = models.DateTimeField(auto_now_add=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auctions")
    bid = models.ManyToManyField(Bid, blank=True, related_name="bids")
    comments = models.ManyToManyField(Commit, blank=True, related_name="comments")
    
    def __str__(self):
        return f"{self.title_item}"

class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Watchlist_user")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction")

    def __str__(self):
        return f"{self.user}: {self.auction}"

auctions/forms.py
from django.forms import ModelForm

from auctions.models import Auction
from .models import *

class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ['title_item', 'description_item', 'category', 'image_URL', 'start_price', 'durations']

class CommitForm(ModelForm):
    class Meta:
        model = Commit
        fields = ['comment']

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['bid']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from .forms import *


def index(request):
    return render(request, "auctions/index.html", {
        "all_auctions": Auction.objects.filter(closed=False)
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="/login")
def create_auction(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = AuctionForm(request.POST)
        # if form is valid
        if form.is_valid():
            # try save db
            try:
                new_auction = form.save(commit=False)
                new_auction.user = user
                new_auction.save()
            # if integrity Error
            except IntegrityError:
                return render(request, "auctions/create.html", {
                    "form": form,
                    "message": "We were unable to add the auction"
                })
            messages.add_message(request, messages.SUCCESS, "Success! Your auction has been created.", extra_tags="alert alert-success")
            return HttpResponseRedirect(reverse("index"))    
        # if form is not valid
        else:
            messages.add_message(request, messages.WARNING, "Something went wrong. Please try again.", extra_tags="alert alert-danger")
            return render(request, "auctions/create.html", {
                "form": form
            })
    else:
        return render(request, "auctions/create.html", {
            "form": AuctionForm()
        })


@login_required(login_url="/login")
def auctions(request, auction_id):
    auction = Auction.objects.get(id=auction_id)
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        if request.POST.get("button") == "Watchlist":
            if not user.Watchlist_user.filter(auction=auction):
                watchlist = WatchList()
                watchlist.user = user
                watchlist.auction = auction
                watchlist.save()
                messages.add_message(request, messages.SUCCESS, "This auction has been added in your watchlist.", extra_tags="alert alert-success")
            else:
                user.Watchlist_user.filter(auction=auction).delete()
                messages.add_message(request, messages.SUCCESS, "This auction has been deleted to your watchlist.", extra_tags="alert alert-danger")
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        if request.POST.get("button") == "Comment":
            form = CommitForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = user
                comment.save()
                auction.comments.add(comment)
                auction.save()
                messages.add_message(request, messages.SUCCESS, "Your comment has been added.", extra_tags="alert alert-success")
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        if not auction.closed:
            if request.POST.get("button") == "Close":
                auction.closed = True
                auction.save()
                messages.add_message(request, messages.SUCCESS, "Your auction is now closed.", extra_tags="alert alert-danger")
            else:
                price = float(request.POST["bid"])
                if user.username != auction.user.username:
                    if not auction.bid.exists():
                        if float(price) <= float(auction.start_price):
                            messages.add_message(request, messages.WARNING, "Error: invalid bid amount.", extra_tags="alert alert-danger")
                            return render(request, "auctions/auction.html", {
                                "auction": auction,
                                "formBid": BidForm(),
                                "commitForm": CommitForm()
                            })
                        else:
                            formBid = BidForm(request.POST)
                            if formBid.is_valid():
                                bid = formBid.save(commit=False)
                                bid.user = user
                                bid.save()
                                auction.bid.add(bid)
                                auction.save()
                                messages.add_message(request, messages.SUCCESS, "Your bid is placed.", extra_tags="alert alert-success")
                            else:
                                return render(request, 'auctions/auction.html', {
                                    "formBid": formBid,
                                    "commitForm": CommitForm()
                                })
                    elif float(price) <= float(auction.bid.last().bid):
                            messages.add_message(request, messages.WARNING, "Error: invalid bid amount.", extra_tags="alert alert-danger")
                            return render(request, "auctions/auction.html", {
                                "auction": auction,
                                "formBid": BidForm(),
                                "commitForm": CommitForm()
                            })
                    else:
                        formBid = BidForm(request.POST)
                        if formBid.is_valid():
                            bid = formBid.save(commit=False)
                            bid.user = user
                            bid.save()
                            auction.bid.add(bid)
                            auction.save()
                            messages.add_message(request, messages.SUCCESS, "Your bid is placed.", extra_tags="alert alert-success")
                        else:
                            return render(request, 'auctions/auction.html', {
                                "formBid": formBid,
                                "commitForm": CommitForm()
                            })
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        return render(request, "auctions/auction.html", {
            "auction": auction,
            "formBid": BidForm(),
            "commitForm": CommitForm()
        })                

def categories(request):
    if request.POST.get("button") == "Filter":
        category = request.POST["category"]
        auctions = Auction.objects.filter(category=category)
        return render(request, 'auctions/categories.html', {
            "form": AuctionForm(),
            "auctions": auctions
        })
    return render(request, 'auctions/categories.html', {
        "form": AuctionForm()
    })

@login_required(login_url="/login")
def watchlist(request):
    product = WatchList.objects.filter(user=request.user)
    auctions_id = WatchList.objects.values_list('auction', flat=True)
    auctions = Auction.objects.filter(pk__in=auctions_id)
    return render(request, "auctions/watchlist.html", {
        "watchlist": product,
        "auctions": auctions
    })

auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if messages %}
        <div class="messages m-4">
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}">{% endif %}{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    {% if auction.closed %}
    <div class="alert alert-info" role="alert">
        Auction closed
    </div>
        {% if auction.bid.last.user.username %}
        <strong>Winner: </strong>{{ auction.bid.last.user.username }}
        {% else %}
        <strong>No body win this auction. </strong>
        {% endif %}
    {% endif %}
    <h2 style="text-align: center; margin:20px">{{ auction.title_item }}</h2>
        <div style="text-align: center; margin:20px">
        <tr>
            <td style="width:40px">
                <img src="{{ auction.image_URL }}" alt="img" style="max-height: 600px;">
            </td>
            <td>
                <div>{{ auction.description_item }}</div>
                {% if auction.bid.last %}
                    <div><strong>Bid : {{ auction.bid.last.bid }}$</strong></div>
                    <div>Best bid by : {{ auction.bid.last.user.username }}</div>
                {% else %}
                    <div>No bid again, let's be the first to bid.</div>
                {% endif %}
                <div>Start price : {{ auction.start_price }}$</div>
                <div>Duration : {{ auction.durations }} days</div>
            </td>
        </tr>
        {% if user.username != auction.user.username and not auction.closed %}
        <form action="{% url 'auction' auction.id %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ formBid }}
            <input type="submit" value="Bid" class="btn btn-primary">
        </form>
        <form action="{% url 'auction' auction.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" name="button" class="btn btn-primary" value="Watchlist">Add in your watchlist</button>
        </form>
        {% endif %}
        {% if user.username == auction.user.username and not auction.closed %}
            <form action="{% url 'auction' auction.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="button" class="btn btn-danger" value="Close">Close auction</button>
            </form>        
        {% endif %}
        </div>
        <tr>
            <td>
                <div><small>Listed by: {{ auction.user }}</small></div>
                <div><small>Published {{ auction.time | timesince }} ago - {{ auction.time }}</small></div>
            </td>
        </tr>
        
        {% for comment in auction.comments.all %}
        <hr style="margin-left:30%; margin-right: 30%;">
        <div style="margin-left:31%; margin-right: 30%;">
        
          <article class="media">
            <div class="media-content">
                <div class="content">
                <p>
                    <strong>{{ comment.user }}</strong> <small>@{{ comment.user }}</small>
                    <br>
                    {{ comment.comment }}
                    <br>
                    <small>{{comment.time}}</small>
                </p>
                </div>
            </div>
            </article>
        </div>
        
        
        {% endfor %}
        {% if user.username != auction.user.username %}
        
        <div style="margin-left:30%; margin-right: 30%;">
        <hr>
        <article class="media">
            <div class="media-content">
            <form action="{% url 'auction' auction.id %}" method="POST">
            {% csrf_token %}
                <div class="field">
                <p class="control">
                    <textarea class="textarea"  name="comment" maxlength="512" required id="id_comment" placeholder="Add a comment..."></textarea>
                </p>
                </div>
                <div class="field">
                <p class="control">
                    <button type="submit" name="button" class="btn btn-primary" value="Comment">Post comment</button>
                </p>
                </div>
            </form>
            </div>
            </article>
            </div>
        {% endif %}
    
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% block title %} Categories {% endblock %}

{% block body %}

    <form action="{% url 'categories' %}" enctype="multipart/form-data" method="POST" class="m-3" style="text-align: center;">
        {% csrf_token %}
        Select a category : {{ form.category }}
        <button type="submit" name="button" class="btn btn-primary" value="Filter">Filter</button>
    </form>
    <div class="container">
        <div class="row row-cols-3">
    {% for auction in auctions %}
    <div class="col" style="margin-top:10px; display:flex; align-items: center;">
        
        <div class="card" id="cardtile">
            <div class="card-image pt-3">
              <figure class="image">
                <img src="{{ auction.image_URL }}" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <p class="title is-4"><a href="{% url 'auction' auction.id %}">{{ auction.title_item }}</a></p>
                  <p class="subtitle is-3">
                    {% if auction.bid.last %}
                        Bid : {{ auction.bid.last.bid }}$
                    {% else %}
                        <div>No bid again, let's be the first to bid.</div>
                        Start price : {{ auction.start_price }}$
                    {% endif %}</p>
                </div>
              </div>
              <div class="content">
                <p>{{ auction.description_item }} <a href="#">#{{ auction.title_item}}</a></p>
                
                Listed by <a>@{{auction.user}}</a>.
                
                <br>
                <time datetime="2016-1-1">{{ auction.time }}</time>
              </div>
            </div>
          </div>
        </div>
    {% empty %}
        <div>No auction in this category.</div>
    {% endfor %}
    </div>
    </div>
    

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 style="text-align: center; margin:20px">Create a Auction</h2>
    {% if messages %}
        <div class="messages m-4">
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}">{% endif %}{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <div style="width: 250px; height:auto; margin-left: 45%; margin-top: 50px;">
        <div style="display: flex; flex-direction: column; justify-self: center;">
        <form action="{% url 'create' %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create Auction" class="btn btn-primary">
        </form>
        </div>
    </div>
    {% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 style="text-align: center; margin:20px">Active Listings</h2>
    {% if messages %}
        <div class="messages m-4">
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}">{% endif %}{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="container">
        <div class="row row-cols-3">
          
        {% for auction in all_auctions %}
        <div class="col" style="margin-top:10px; display:flex; align-items: center;">
        
        <div class="card" id="cardtile">
            <div class="card-image pt-3">
              <figure class="image">
                <img src="{{ auction.image_URL }}" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <p class="title is-4"><a href="{% url 'auction' auction.id %}">{{ auction.title_item }}</a></p>
                  <p class="subtitle is-3">
                    {% if auction.bid.last %}
                        Bid : {{ auction.bid.last.bid }}$
                    {% else %}
                        <div>No bid again, let's be the first to bid.</div>
                        Start price : {{ auction.start_price }}$
                    {% endif %}</p>
                </div>
              </div>
              <div class="content">
                <p>{{ auction.description_item }} <a href="#">#{{ auction.title_item}}</a></p>
                
                Listed by <a>@{{auction.user}}</a>.
                
                <br>
                <time datetime="2016-1-1">{{ auction.time }}</time>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
            No active auctions
        {% endfor %}
        
      </div>
    </div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}BLD Shop{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        
        <nav class="navbar is-info" role="navigation" aria-label="main navigation" style="border-radius:10px;">
            <div class="navbar-brand">
              <a class="navbar-item" href="{% url 'index' %}">
                <h1 class="title is-3 titlebrand">BLD Shop</h1>
              </a>
          
              <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
              </a>
            </div>
          
            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-start">
                <a class="navbar-item" href="{% url 'index' %}">
                    
                  </a>
          
                <a class="navbar-item" href="{% url 'index' %}">
                  Active Listings
                </a>
          
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                      More
                  </a>
          
                  <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'categories' %}">
                        Categories
                    </a>
                    
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'create' %}">
                        Create your Auction
                    </a>
                    <a class="navbar-item" href="{% url 'watchlist' %}">
                        Your watchlist
                    </a>
                    
                  </div>
                </div>
              </div>
          
              <div class="navbar-end">
                <div class="navbar-item">
                    <div class="mr-2">
                        {% if user.is_authenticated %}
                            Signed in as <strong>{{ user.username }}</strong>.
                        {% else %}
                            Not signed in.
                        {% endif %}
                    </div>
                  <div class="buttons">
                {% if user.is_authenticated %}  
                    <a class="button is-primary" href="{% url 'logout' %}">
                        <strong>Log out</strong>
                    </a>    
                {% else %}
                    <a class="button is-primary" href="{% url 'register' %}">
                      <strong>Sign up</strong>
                    </a>
                    <a class="button is-light" href="{% url 'login' %}">
                      Log in
                    </a>
                {% endif %}     
                  </div>
                </div>
              </div>
            </div>
          </nav>


        <div class="content p-2">
        {% block body %}
        {% endblock %}
        </div>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 style="text-align: center; margin:20px">Your watchlist: </h2>
    <div class="container">
        <div class="row row-cols-3">
        {% for auction in auctions %}
        <div class="col" style="margin-top:10px; display:flex; align-items: center;">
        
            <div class="card" id="cardtile">
                <div class="card-image pt-3">
                  <figure class="image">
                    <img src="{{ auction.image_URL }}" alt="Placeholder image">
                  </figure>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-left">
                      <p class="title is-4"><a href="{% url 'auction' auction.id %}">{{ auction.title_item }}</a></p>
                      <p class="subtitle is-3">
                        {% if auction.bid.last %}
                            Bid : {{ auction.bid.last.bid }}$
                        {% else %}
                            <div>No bid again, let's be the first to bid.</div>
                            Start price : {{ auction.start_price }}$
                        {% endif %}</p>
                    </div>
                  </div>
                  <div class="content">
                    <p>{{ auction.description_item }} <a href="#">#{{ auction.title_item}}</a></p>
                    
                    Listed by <a>@{{auction.user}}</a>.
                    
                    <br>
                    <time datetime="2016-1-1">{{ auction.time }}</time>
                  </div>
                </div>
              </div>
            </div>
        {% empty %}
            <div>Your watchlist is empty.</div>
        {% endfor %}
        </div>
    </div>
{% endblock %}